# Website settings
url: "https://it.badykov.com"

# Internal nav
nav:
  main:
    profile: "/"
#    music: "/music"
    blog: "/blog"
  blog:
    all: "/blog"
    popular: "/blog/popular"
    tags: "/blog/tags"
    rss: "/feed.xml"

# Bio settings
name: "Marat Badykov"
description: "Hi! My name is Marat Badykov. I'm a full-stack web developer. I like to solve interesting and non-standard tasks, I enjoy writing Php, Ruby, and Js. I created this blog for sharing my thoughts about programming, software engineering and other cool stuff."
thumbnail_path: "profile-photos/marat-badykov.jpg"

# URLs
contact_urls:
  github:
    url: "https://github.com/Marat555"
    label: "GitHub"
    icon: "github-square"
  telegram:
      url: "https://t.me/marat_badykov"
      label: "Telegram"
      icon: "telegram"
  twitter:
    url: "https://twitter.com/marat_badykov"
    label: "Twitter"
    icon: "twitter-square"
  medium:
    url: "https://medium.com/@marat_badykov"
    label: "Medium"
    icon: "medium"
  linkedin:
    url: "https://www.linkedin.com/in/marat-badykov-5921ab162/"
    label: "Linkedin"
    icon: "linkedin-square"
  email:
    url: "mailto:maratcool@mail.ru"
    label: "Email"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/blog/page:num"
permalink: "/blog/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
